### ISSUE TITLE
ModuleNotFoundError: No module named comicreader.local_settings

### ISSUE THREAD

**Issue by nstephenh** [jgasteiz/comic-reader-home#1]
Hello, I'm trying to use this program on my own server. However, after installing the PIP requirements I was unable to run the server. I tried installing via docker first but my docker experience is limited and when I ran the image I built it would run and then stop, with no webserver accessable. Could you please provide some documentation related to the missing module?

Thank you.

`python3.6 manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nsh/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/nsh/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/nsh/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/nsh/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/nsh/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'comicreader.local_settings'
`

**Comment by jgasteiz** [comment]
Hey @nstephenh , sorry for the huge delay replying (I won't blame you if you don't care anymore):

I've updated the README with instructions for running the project in a server, I hope that helps. I've also removed the dockerfile files, because I'm not really using them or keeping them up to date anymore and they're only confusing people.

Let me know if you have any issues running the thing.

**Comment by nstephenh** [comment]
On my debian server, I'm unable to install the pip requirements:
`Downloading/unpacking ipdb==0.10.3 (from -r requirements.txt (line 2))
  Downloading ipdb-0.10.3.tar.gz
  Running setup.py (path:/tmp/pip-build-bute5d77/ipdb/setup.py) egg_info for package ipdb
    error in ipdb setup command: Invalid environment marker: python_version >= "3.3"
    Complete output from command python setup.py egg_info:
    error in ipdb setup command: Invalid environment marker: python_version >= "3.3"`

I tried installing on my laptop and it worked, but I had to run ./manage.py migrate to create a database first, otherwise I'd get database errors.

**Comment by jgasteiz** [comment]
It looks like your debian server python 3 version is old? Maybe take a look at this to make sure you can have an updated python3 version installed there: https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-debian-8

Alternatively, try to run `pip3 install -r requirements.txt`, but I don't think that should be necessary, because you're already on a python3 virtualenv.

I'll update the README with the `./manage.py migrate` command, I completely forgot about it. Cheers!

**Comment by jgasteiz** [comment]
Closing this for now.
